stages:
  - build_ci_image
  - tests
  - integration_tests
  - build_tests

build_ci_image:
  stage: build_ci_image
  image: harbor.windmaker.net/limani/base_docker:latest
  before_script:
    - echo "$GIT_CRYPT_KEY_B64" | base64 -d | git-crypt unlock -
    - source config/common.env
    - source config/ci.env
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends unzip wget ca-certificates
    - wget -O /tmp/argbash.zip https://github.com/matejak/argbash/archive/refs/tags/2.11.0.zip
    - unzip /tmp/argbash.zip -d /tmp
    - cp /tmp/argbash-2.11.0/bin/argbash argbash
    - export IMAGE_NAME=karavomarangos_ci
    - export IS_BASE_IMAGE=1
    - docker-build
  only:
    - /^ci(-|_).*$/

validate_json_files:
  stage: tests
  image: harbor.windmaker.net/karavomarangos/karavomarangos_ci:latest
  script:
    - bash tests/validate_examples_test.sh
  except:
    - /^ci(-|_).*$/

validate_package_libs:
  stage: tests
  image: harbor.windmaker.net/karavomarangos/karavomarangos_ci:latest
  script:
    - bash tests/validate_packages_lib.sh
  except:
    - /^ci(-|_).*$/

test_containers_lib:
  stage: tests
  image: harbor.windmaker.net/karavomarangos/karavomarangos_ci:latest
  script:
    - bash tests/validate_containers_lib.sh
  except:
    - /^ci(-|_).*$/

test_package_version_retrieval_from_container:
  stage: integration_tests
  image: harbor.windmaker.net/karavomarangos/karavomarangos_ci:latest
  script:
    - bash tests/validate_package_retrieval.sh
    - bash tests/validate_package_list_update.sh
    - bash tests/validate_gpg_and_repo_functions.sh
  except:
    - /^ci(-|_).*$/

test_build:
  stage: build_tests
  image: harbor.windmaker.net/karavomarangos/karavomarangos_ci:latest
  script:
    - source config/common.env
    - bash tests/validate_build.sh
  except:
    - /^ci(-|_).*$/
