# Argbash template for karavomarangos argument parsing.
# Generate with: argbash lib/05-argbash.m4 -o lib/05-argbash.sh --strip user-content
#
# ARG_OPTIONAL_SINGLE([json-file],[],[Path to the JSON image definition file],[])
# ARG_OPTIONAL_BOOLEAN([update-packages],[],[Update package versions in the JSON file],[on])
# ARG_OPTIONAL_BOOLEAN([update-dockerfile],[],[Generate/update the Dockerfile],[on])
# ARG_OPTIONAL_SINGLE([dockerfile-output],[],[Path where to render the Dockerfile],[Dockerfile])
# ARG_OPTIONAL_BOOLEAN([update-readme],[],[Update the image README (not yet supported)],[off])
# ARG_OPTIONAL_SINGLE([readme-output],[],[Path where to render the README (not yet supported)],[README.md])
# ARG_HELP([Karavomarangos — manage Limani Docker image definitions])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info

die() {
  local _ret="${2:-1}"
  test "${_PRINT_HELP:-no}" = yes && print_help >&2
  echo "$1" >&2
  exit "${_ret}"
}

begins_with_short_option() {
  local first_option all_short_options='h'
  first_option="${1:0:1}"
  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_json_file=
_arg_update_packages="on"
_arg_update_dockerfile="on"
_arg_dockerfile_output="Dockerfile"
_arg_update_readme="off"
_arg_readme_output="README.md"

print_help() {
  printf '%s\n' "Karavomarangos — manage Limani Docker image definitions"
  printf 'Usage: %s [--json-file <arg>] [--(no-)update-packages] [--(no-)update-dockerfile] [--dockerfile-output <arg>] [--(no-)update-readme] [--readme-output <arg>] [-h|--help]\n' "$0"
  printf '\t%s\n' "--json-file: Path to the JSON image definition file (no default)"
  printf '\t%s\n' "--update-packages, --no-update-packages: Update package versions in the JSON file (on by default)"
  printf '\t%s\n' "--update-dockerfile, --no-update-dockerfile: Generate/update the Dockerfile (on by default)"
  printf '\t%s\n' "--dockerfile-output: Path where to render the Dockerfile (default: 'Dockerfile')"
  printf '\t%s\n' "--update-readme, --no-update-readme: Update the image README (not yet supported) (off by default)"
  printf '\t%s\n' "--readme-output: Path where to render the README (not yet supported) (default: 'README.md')"
  printf '\t%s\n' "-h, --help: Prints help"
}

parse_commandline() {
  local _key
  while test $# -gt 0; do
    _key="$1"
    case "$_key" in
    --json-file)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_json_file="$2"
      shift
      ;;
    --json-file=*)
      _arg_json_file="${_key##--json-file=}"
      ;;
    --no-update-packages | --update-packages)
      _arg_update_packages="on"
      test "${1:0:5}" = "--no-" && _arg_update_packages="off"
      ;;
    --no-update-dockerfile | --update-dockerfile)
      _arg_update_dockerfile="on"
      test "${1:0:5}" = "--no-" && _arg_update_dockerfile="off"
      ;;
    --dockerfile-output)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_dockerfile_output="$2"
      shift
      ;;
    --dockerfile-output=*)
      _arg_dockerfile_output="${_key##--dockerfile-output=}"
      ;;
    --no-update-readme | --update-readme)
      _arg_update_readme="on"
      test "${1:0:5}" = "--no-" && _arg_update_readme="off"
      ;;
    --readme-output)
      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
      _arg_readme_output="$2"
      shift
      ;;
    --readme-output=*)
      _arg_readme_output="${_key##--readme-output=}"
      ;;
    -h | --help)
      print_help
      exit 0
      ;;
    -h*)
      print_help
      exit 0
      ;;
    *)
      _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
      ;;
    esac
    shift
  done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
