# Dockerfile generated using karavomarangos - https://git.windmaker.net/a-castellano/karavomarangos
ARG BASE_IMAGE={{ .config.base_image }}
FROM $BASE_IMAGE

MAINTAINER {{ .config.maintainer.name }} {{ .config.maintainer.surname }} <{{ .config.maintainer.email }}>

RUN \
  apt-get update -qq && \
{{- if has .config "required_repositories" }}
  apt-get install -qq -o=Dpkg::Use-Pty=0 -y gnupg ca-certificates wget --no-install-recommends && \
{{- if has .config.required_repositories "gpg_keyring" }}
{{- if eq .config.required_repositories.gpg_keyring.content.type "key" }}
{{- range .config.required_repositories.gpg_keyring.content.data }}
  gpg --keyserver keyserver.ubuntu.com --recv-keys {{ . }} && \
{{- end }}
  gpg --export {{ range .config.required_repositories.gpg_keyring.content.data -}}
{{ . }} {{ end -}}| gpg --dearmor > /etc/apt/keyrings/{{ .config.required_repositories.gpg_keyring.name }}.gpg && \
{{- end }}
{{- end }}
{{- $repo_name := .config.required_repositories.name -}}
{{- range .config.required_repositories.apt_lines }}
  echo "{{ . }}" >> /etc/apt/sources.list.d/{{ $repo_name }}.list && \
{{- end }}
{{- end }}
{{- if has .config "packages" }}
{{- if has .config "required_repositories" }}
  apt-get update -qq && \
{{- end }}
  apt-get install -qq -o=Dpkg::Use-Pty=0 -y \
{{- range .config.packages }}
    {{ .name }}{{- if has . "version" -}}={{.version}}{{- end }} \
{{- end }}
    --no-install-recommends && \
{{- end }}
