# Dockerfile generated using karavomarangos - https://git.windmaker.net/a-castellano/karavomarangos
ARG BASE_IMAGE={{ .config.base_image }}
FROM $BASE_IMAGE

MAINTAINER {{ .config.maintainer.name }} {{ .config.maintainer.surname }} <{{ .config.maintainer.email }}>
{{ if has .config "copy" -}}
{{- range .config.copy }}
COPY {{ .source }}={{ .destination }}
{{- end }}
{{- end }}

{{ $is_ca_certificates_installed := false -}}
{{- $has_commands := false -}}
{{- if has .config "extra_commands" -}}
{{- $has_commands = true -}}
{{- else -}}
{{- $has_commands = false -}}
{{ end -}}
RUN \
{{- if has .config "build_environment_variables" -}}
{{- range .config.build_environment_variables }}
  export {{ .name }}={{ .value }} && \
{{- end }}
{{- end }}
{{- if has .config "debconf_selections" -}}
{{- range .config.debconf_selections }}
  echo {{ .package }} {{ .question }} {{ .type }} {{ .value }} | debconf-set-selections && \
{{- end }}
{{- end }}
  apt-get update -qq && \
{{- if has .config "required_repositories" }}
  apt-get install -qq -o=Dpkg::Use-Pty=0 -y gnupg ca-certificates wget --no-install-recommends && \
{{- if has .config.required_repositories "gpg_keyring" }}
{{- if eq .config.required_repositories.gpg_keyring.content.type "key" }}
{{- range .config.required_repositories.gpg_keyring.content.data }}
  gpg --keyserver keyserver.ubuntu.com --recv-keys {{ . }} && \
{{- end }}
  gpg --export {{ range .config.required_repositories.gpg_keyring.content.data -}}
{{ . }} {{ end -}}| gpg --dearmor > /etc/apt/keyrings/{{ .config.required_repositories.gpg_keyring.name }}.gpg && \
{{- end }}
{{- end }}
{{- if eq .config.required_repositories.gpg_keyring.content.type "url" }}
{{- $gpg_name := .config.required_repositories.gpg_keyring.name -}}
{{- range .config.required_repositories.gpg_keyring.content.data }}
  wget -qO- {{ . }} >> /etc/apt/keyrings/{{ $gpg_name }}.gpg && \
{{- end }}
{{- end }}
{{- $repo_name := .config.required_repositories.name -}}
{{- range .config.required_repositories.apt_lines }}
  echo "{{ . }}" >> /etc/apt/sources.list.d/{{ $repo_name }}.list && \
{{- end }}
{{- end }}
{{- $has_packages := false -}}
{{- $has_repos := false -}}
{{- if has .config "packages" }}
{{- $has_packages = true -}}
{{- end -}}
{{- if has .config "required_repositories" -}}
{{ $has_repos = true -}}
{{- end -}}
{{- if eq $has_packages true -}}
{{- if eq $has_repos true }}
  apt-get update -qq && \
{{- end }}
  apt-get install -qq -o=Dpkg::Use-Pty=0 -y \
{{- range .config.packages }}
{{- if eq .name "ca-certificates" -}}{{- $is_ca_certificates_installed = true -}}{{ end }}
    {{ .name }}{{- if has . "version" -}}={{.version}}{{- end }} \
{{- end }}
    --no-install-recommends && \
  apt-get purge -qq -o=Dpkg::Use-Pty=0 -y gnupg wget {{ if not $is_ca_certificates_installed -}}ca-certificates{{- end }} && \
  apt-get autoremove -qq -o=Dpkg::Use-Pty=0 -y && \
  apt-get autoclean -qq -o=Dpkg::Use-Pty=0 -y && \
  rm -rf /var/lib/apt/lists/* {{ if eq $has_commands true -}}&& \{{ end }}
{{- else -}}
{{- if eq $has_repos true }}
  apt-get update -qq && \
  apt-get purge -qq -o=Dpkg::Use-Pty=0 -y gnupg wget ca-certificates && \
  apt-get autoremove -qq -o=Dpkg::Use-Pty=0 -y && \
  apt-get autoclean -qq -o=Dpkg::Use-Pty=0 -y && \
  rm -rf /var/lib/apt/lists/* {{ if eq $has_commands true -}}&& \{{ end }}
{{- end -}}
{{- end -}}
{{- if eq $has_commands true -}}
{{- $final_command := len .config.extra_commands -}}
{{- $current_command := 1 -}}
{{- range .config.extra_commands }}
  {{ . }} {{ if ne $final_command $current_command -}}&& \{{ end }}
{{- $current_command = $current_command | add 1 -}}
{{- end }}
{{- end }}
{{ if has .config "user" }}
USER {{ .config.user }}
{{- end -}}
{{ if has .config "environment_variables" }}
ENV {{ range .config.environment_variables }}{{ .name }}={{ .value }} {{ end }}
{{- end -}}
{{ if has .config "exposed_ports" }}
EXPOSE {{ range .config.exposed_ports }}{{ . }} {{ end }}
{{- end -}}
{{ if has .config "command" }}
{{ $final_command := len .config.command -}}
{{ $current_command := 1 -}}
CMD [{{ range .config.command }}"{{ . }}"{{- if ne $current_command $final_command }}, {{ end -}}{{- $current_command = $current_command | add 1 -}}{{ end }}]
{{- end -}}
